---
# tasks file for php
- name: apt update
  become: true
  apt:
   upgrade: yes
   update_cache: yes
- name: Install wget
  apt:
   name: wget
   state: present
- name: Install Apache
  apt:
   name: apache2
   state: present
- name: Install ufw
  apt:
   name: ufw
   state: present
- name: enable UFW
  ufw:
   state: enabled
- name: allow Openssh
  ufw:
   rule: allow
   name: OpenSSH
- name: allow port 80
  ufw:
   rule: allow
   port: '80'
   proto: tcp
- name: allow port 443
  ufw:
   rule: allow
   port: '443'
- name: install lsb-release apt-transport-https ca-certificates
  apt:
   name:
    - lsb-release
    - apt-transport-https
    - ca-certificates
   state: present
- name: get php respository
  shell:  wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
- name: add the repo
  command: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
- name: Install php and the dependencies
  apt:
    name:
      - php
      - libapache2-mod-php
      - php8.1-mysql
      - php8.1-common
      - php8.1-mysql
      - php8.1-xml
      - php8.1-xmlrpc
      - php8.1-curl
      - php8.1-gd
      - php8.1-imagick
      - php8.1-cli
      - php8.1-dev
      - php8.1-imap
      - php8.1-mbstring
      - php8.1-opcache
      - php8.1-soap
      - php8.1-zip
      - php8.1-intl
    state: present
